const imageMapping = {
    Aberdeen: require('./images/Aberdeen.jpg'),
    Amsterdam: require('./images/Amsterdam.jpg'),
    Athens: require('./images/Athens.jpg'),
    Auschwitz: require('./images/Auschwitz.jpg'),
    Barcelona: require('./images/Barcelona.jpg'),
    Bath: require('./images/Bath.jpg'),
    Belfast: require('./images/Belfast.jpg'),
    'Belo Horizonte': require('./images/Belo_Horizonte.jpg'),
    Berlin: require('./images/Berlin.jpg'),
    Blumenau: require('./images/Blumenau.jpg'),
    Bratislava: require('./images/Bratislava.jpg'),
    Brussels: require('./images/Brussels.jpg'),
    Bucharest: require('./images/Bucharest.jpg'),
    Budapest: require('./images/Budapest.jpg'),
    'Cabo da Roca': require('./images/Cabo_da_Roca.jpg'),
    Cappadocia: require('./images/Cappadocia.jpg'),
    Chania: require('./images/Chania.jpg'),
    'Ciudad del Este': require('./images/Ciudad_del_Este.jpg'),
    'Cliffs of Moher': require('./images/Cliffs_of_Moher.jpg'),
    'Porto de Sauipe': require('./images/Costa_do_Sauipe.jpg'),
    'Dead Sea': require('./images/Dead_Sea.jpg'),
    Dresden: require('./images/Dresden.jpg'),
    Dublin: require('./images/Dublin.jpg'),
    'City of Edinburgh': require('./images/Edinburgh.jpg'),
    'Elafonissi Beach': require('./images/Elafonissi.jpg'),
    Florence: require('./images/Florence.jpg'),
    'Frankfurt am Main': require('./images/Frankfurt.jpg'),
    Gardaland: require('./images/Gardaland.jpg'),
    'Giants Causeway': require('./images/Giants_Causeway.jpg'),
    'Glasgow City': require('./images/Glasgow.jpg'),
    Heraklion: require('./images/Heraklion.jpg'),
    Inhotim: require('./images/Inhotim.jpg'),
    Istanbul: require('./images/Istanbul.jpg'),
    Jerusalem: require('./images/Jerusalem.jpg'),
    Krakow: require('./images/Krakow.jpg'),
    'Lake District': require('./images/Lake_District.jpg'),
    'Lands End': require('./images/Land_End.jpg'),
    Lisbon: require('./images/Lisboa.jpg'),
    London: require('./images/London.jpg'),
    Marrakesh: require('./images/Marrakesh.jpg'),
    Merzouga: require('./images/Merzouga.jpg'),
    Moscow: require('./images/Moscow.jpg'),
    Munich: require('./images/Munich.jpg'),
    'Newcastle upon Tyne': require('./images/Newcastle.jpg'),
    Nuremberg: require('./images/Nuremberg.jpg'),
    Pamukkale: require('./images/Pamukkale.jpg'),
    Paphos: require('./images/Paphos.jpg'),
    Paris: require('./images/Paris.jpg'),
    Plitvice: require('./images/Plitvice.jpg'),
    Porto: require('./images/Porto.jpg'),
    'Porto Seguro': require('./images/Porto_Seguro.jpg'),
    Prague: require('./images/Prague.jpg'),
    'Rio de Janeiro': require('./images/Rio_de_Janeiro.jpg'),
    'Citta di San Marino': require('./images/San_Marino.jpg'),
    Schmalkalden: require('./images/Schmalkalden.jpg'),
    Sestriere: require('./images/Sestriere.jpg'),
    Sofia: require('./images/Sofia.jpg'),
    Stonehenge: require('./images/Stonehenge.jpg'),
    'Tel Aviv-Yafo': require('./images/Tel_Aviv.jpg'),
    Tiradentes: require('./images/Tiradentes.jpg'),
    Torino: require('./images/Turin.jpg'),
    Ferret: require('./images/Val_Ferret.jpg'),
    Venice: require('./images/Venice.jpg'),
    Vesuvio: require('./images/Vesuvio.jpg'),
    Vienna: require('./images/Vienna.jpg'),
    Zagreb: require('./images/Zagreb.jpg'),
    Zurich: require('./images/Zurich.jpg')
}
export default imageMapping
